s1 = {1, 2, 3, 4, 5}
s2 = {2, 3, 4}
s3 = {0, 1, 2, 3, 4, 5, 6}
print(s1)
print(s2)
print(s3)
print("----------")
print(s1.issuperset(s2))
print(s1.issubset(s2))
print(s1.isdisjoint(s2))
print("----------")
print(s2.issuperset(s1))
print(s2.issubset(s1))
print(s2.isdisjoint(s1))
print("----------")
print(s1.issuperset(s3))
print(s1.issubset(s3))
print(s1.isdisjoint(s3))
print("----------")
print(s3.issuperset(s1))
print(s3.issubset(s1))
print(s3.isdisjoint(s1))
print("----------")
print(s2.issuperset(s3))
print(s2.issubset(s3))
print(s2.isdisjoint(s3))
print("----------")
print(s3.issuperset(s2))
print(s3.issubset(s2))
print(s3.isdisjoint(s2))
