place = input("Enter the place visited by the family: ")
dangerous_situation = input("Enter the situation or being faced: ")
action_of_son = input("Enter son's reaction in the situation: ")
action_of_mother = input("Enter mother's reaction in the situation: ")
word_for_courage = input("Enter word for courage showed by the father: ")
retaliation_of_father = input("Enter father's reaction in the situation: ")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print(f"Once upon a time, a family of three went to {place}.")
print(f"They faced a {dangerous_situation} there!")
print(f"The son was really scared and {action_of_son}.")
print(f"The mother was scared but less than the son. She {action_of_mother}.")
print(f"However, the father was really {word_for_courage}.")
print(f"He {retaliation_of_father} the {dangerous_situation}, and the {dangerous_situation} went away in a jiffy!")